### ISSUE TITLE
Remove default Gravity Form default CSS 

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1030]
Right now we have the GravityForms plugin defaulting to output CSS, which isn't necessary given that we are also building our own assets. And why load in another CSS file if we don't have to? We should make sure things don't look drastically broken however.

**Comment by michaelschofield** [comment]
The gravity form on the referrals page looks poor without the CSS https://miami.wbudevelop.wpengine.com/invitation/123456789/ 

I still need to check _polls_ and identify other forms.

**Comment by michaelschofield** [comment]
The gravity forms break _enough_ that I'm going to leave the CSS for now. There's no way to load it conditionally only when the gravity form is on the page, and without that we'll need to write new CSS for gravity form styles. 

I think the best approach with the most minimal overhead is to just ween off our use of gravity forms for everything but the most predictable things, so that we can deliberately enqueue styles and scripts only on _pages_ or a different post type. 

I think the chief outliers right now are the referral form and anywhere we've used campaign forms, but we need to swap those out first.
