### ISSUE TITLE
formatting of The Incline newsletter template is off

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1115]
### Reproduction
In preview on some mail clients, the newsletter is cutting off text and requiring a long horizontal scroll (please see screenshots in #pit-newsletter) channel. However, it is working completely normally in other mail clients.

Please review the mailchimp template and see if there is something missing (Rebekah suggested a missing media query possibly).

### Suggested priority
priority-high

### Stakeholders
*Submitted:* rossilynne

### Definition of done
How will we know when this feature is complete?

**Comment by michaelschofield** [comment]
@carogea Heya. When you get up and about (no rush), do you mind investigating? I want to give you the totes discretion to be like, hey, tech team, this needs to be done _right now_ or maybe it can wait. It was marked _high_ instead of _critical_ so I'm trying to practice _not looking at it_ and getting distracted lol.

**Comment by carogea** [comment]
@michaelschofield checking it out

**Comment by carogea** [comment]
hey @kassanj @michaelschofield i'd say one of you should check this out today and see if there's an obvious fix. since it's not totally blocking people from reading the newsletter and seems to be an issue for only a few browsers i'd say it can wait a bit if it's not an obvious fix. 

for context i migrated over the templates from their old mailchimp and didn't touch any of them

**Comment by michaelschofield** [comment]
@carogea Alrighty I figured it out and let the other folks know. Basically, the instagram image in there was missing a `width: 100%;` attribute, which would let the image flex and squish with the container size. Without, it was just rendering full width, stretching the email out.
