### ISSUE TITLE
Consider using AMP for Email

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1125]
https://amp.dev/documentation/guides-and-tutorials/?format=email

## DOD
Yes, no, or not right now

**Comment by michaelschofield** [comment]
I think AMP for Emails is actually pretty cool in terms of the performance boost, but I can't recommend it's something we implement. Amp is Gmail-exclusive, which give or take is half of our subscriber-base, but I worry we'd mess up support for the other half, given the requirement to replace taxing HTML elements -- like `<img>` with `<amp-img>` -- and other custom components. 

Since we still have a not-insignificant portion of our users using old email clients, I feel like we would introduce amp at their expensive for minimum return on our time, trial, and error.

@ErnieAtLYD
