### ISSUE TITLE
event embed (future of)

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1396]
## Feature or problem
Describe the feature or problem here.

### Reproduction
Event embed tool in wordpress is broken. details 

https://github.com/wherebyus/frodo/tree/develop/wp-content/plugins/wbu-infobox

shortcode `infobox_event_shortcode`.

“Add infobox” -> Event 

### Suggested expected behavior
please consider fixing the ability to embed events

### Suggested priority
priority-low

### Stakeholders
*Submitted:* rossilynne

### Definition of done
How will we know when this feature is complete?

### Subtasks
A detailed list of changes that need to be made or subtasks. One checkbox per.
- [ ] Brew the coffee

## Developer estimate
To help the team accurately estimate the complexity of this task, 
take a moment to walk through this list and estimate each item. At the end, you can total
the estimates and round to the nearest prime number. 

If any of these are at a `5` or higher, or if the total is above a `5`, consider breaking
this issue into multiple smaller issues.

- [ ] Changes to the database ()
- [ ] Changes to the API ()
- [ ] Testing Changes to the API ()
- [ ] Changes to Application Code ()
- [ ] Adding or updating unit tests ()
- [ ] Local developer testing ()

## Additional estimate
- [ ] Code review ()
- [ ] QA Testing ()
- [ ] Stakeholder Sign-off ()
- [ ] Deploy to Production ()

## QA Notes
Detailed instructions for testing, one checkbox per test to be completed.

### Contextual tests
- [ ] Accessibility check
- [ ] Cross-browser check (Edge, Chrome, Firefox)
- [ ] Responsive check

**Comment by michaelschofield** [comment]
The issue is that a shortcode we have `[infobox_event_shortcode]` fail to embed an event properly. This is a shortcode whose support was abandoned, not intentionally but just by people forgetting it was there. Work was probably last done on it before I got here, so it's probably been a couple years since it's been touched.

*I suggest we remove this shortcode and its functionality entirely*, because it being present is just confusing, and commit to re-add the feature to embed an event in a post only when we have a real _event_ platform roadmap. (edited)

**Comment by ErnieAtLYD** [comment]
via Slack: Regarding https://github.com/wherebyus/general-tasks/issues/1396 @Carolyn Gearig The issue is that a shortcode we have `[infobox_event_shortcode]` fail to embed an event properly. This is a shortcode whose support was abandoned, not intentionally but just by people forgetting it was there. Work was probably last done on it before I got here, so it's probably been a couple years since it's been touched.

*I suggest we remove this shortcode and its functionality entirely*, because it being present is just confusing, and commit to re-add the feature to embed an event in a post only when we have a real _event_ platform roadmap. (edited)

**Comment by michaelschofield** [comment]
@ErnieAtLYD @carogea FYI I network deactivated the Infobox plugin for the time being and moving this ticket to "done".
