### ISSUE TITLE
Automatically identify new ambassadors

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#854]
One option: Automatically toggle ambassadorship when a user achieves their 5th referral, and set a `becameAmbassadorDate` so Briana and Kristem can just look at a list of new ambassadors in a certain timeframe.

DOD: API endpoint?

Suggested by michael

**Comment by ErnieAtLYD** [comment]
Related to #895.

**Comment by michaelschofield** [comment]
## QA
1. Create a new account on your site of choice. 
2. Use your new account's invitation code to subscribe 5 or more new accounts
3. Expect that all subscribers are subscribed without a hassle, and you see a thank you confirmation
4. Expect that your new account gets 5 or more referrals credited to them
5. Upon their fifth referral, confirm that the user is awarded ambassador status
6. Navigate to /wp-json/whereby/api/ambassadors and confirm that your user appears there
7. Add `?count` and `?since=20190102` (etc) query parameters and confirm that the list of ambassadors fluctuates as expected
Note: Ambassadorship is only awarded upon new referrals, so old accounts that have a lot of referrals don't technically have these values. Upon their next referral, status should be awarded.

8. Navigate to tools => Scheduled Actions and confirm that there are a bunch in there \m/. 
9. Sanity check and click around / do other things with referrals and ensure everything is gravy.
