### ISSUE TITLE
Increase the size of sponsor logos on the Post Collection header and sponsor block on WP

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#855]
## Reproduction Steps
Check out a sponsored project such as https://thenewtropic.com/spotlight-on-overtown/. The logo in the  post collection header has a couple issues.

1) it says  "SPONSORED  BY" but should  say "MADE POSSIBLE BY" to match the sponsor block on the right-hand side.

2) the logo size is too small, and with non-horizontal logos (such as a square logo), it's illegible, which looks bad and makes sponsors all angry like

## Expected Results
The logo should be larger. It can also go below the title, if we want, or somewhere less prominent. 

### Additional information:
Sopher sez
> i wanted to add a note on the sponsor logos one above that we consider making  the logo a full break on text, instead of doing the float-left that we are doing now, because it looks wonky on some logos/window sizes
> Some other notes -- this will probably eventually be rolled under promos, so images might have similar standards over time. We might want to consider consolidating these over time.

 - BTID-428
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recrsnrifhfrWgFpM) - (may include image attachments)

### Submitted by
Name: Christopher Sopher 
Email: chris@whereby.us
Slack ID: cksopher

**Comment by michaelschofield** [comment]
Hey there @carogea, when you have some time can you set priorities for this and other backlog items that need prioritization?

**Comment by carogea** [comment]
@michaelschofield yep! i gave this medium priority bc it seems like it's somewhat important bc revenue implications

**Comment by kassanj** [comment]
This ticket is unnecessary. Sopher asked me to remove the sponsor content found on the guide headers, which is addressed in the following ticket: https://app.zenhub.com/workspaces/tech-team-repos-5b3b863cf36bf13b2ad5b66e/issues/wherebyus/general-tasks/856

Here is our conversation:

cksopher [9:35 AM]
hey there

it should go somewhere in the sponsor block on the right-hand side
where is up to y'all, but i assume below the text, and above the "read about our policy" would be ideal?
it could also be hyperlinked text, if better from a ux perspective, than a button
just needs to be a clear call-to-action for the user

also, small thing, but the sponsor tag above the title "Spotlight on Overtown" could be removed or made optional. since we're making the sponsor bug on the right side more awesome by adding this call to action.
