### ISSUE TITLE
add a “Support our Sponsor”  button to the sponsor block on WP

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#856]
## FEATURE REQUEST

We want to add a button (or text hyperlink if preferred for UX/UI reasons) to the sponsor block on WP. This should say "Support our sponsor" by default. That text could  be fixed, or it could be changeable by the person creating the sponsor block (Making it changeable is not high priority and could be done later, depending on  difficulty) 

The user creating the sponsor block in the  WP backend should be able to add a custom hyperlink of their choosing, which the button/link would point to. 

We also need an easy way to track clicks to this link, via  GA  or  another tool. 

### Additional information:
 - BTID-429
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/rechnwe7m0csjLh2b) - (may include image attachments)

### Submitted by
Name: Christopher Sopher 
Email: chris@whereby.us
Slack ID: cksopher

**Comment by kassanj** [comment]
Blocked: I need more deets.

**Comment by kassanj** [comment]
Reached out to Sopher. 

cksopher [9:35 AM]
hey there

it should go somewhere in the sponsor block on the right-hand side
where is up to y'all, but i assume _below_ the text, and _above_ the "read about our policy" would be ideal?
it could also be hyperlinked text, if better from a ux perspective, than a button
just needs to be a clear call-to-action for the user

also, small thing, but the sponsor tag above the title "Spotlight on Overtown" could be removed or made optional. since we're making the sponsor bug on the right side more awesome by adding this call to action.

**Comment by michaelschofield** [comment]
@kassanj Heya. When you have a moment I need something to QA.

**Comment by kassanj** [comment]
### QA Notes

1. Visit http://miami.wbudevelop.wpengine.com/neighborhood-guide-lincoln-road/
EXPECT: The sponsor block on the header to have been removed.
EXPECT: The aside sponsor block to have a `Support our Sponsor` text hyperlinked to an external page.
