### ISSUE TITLE
Footer duplication in redesign

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#876]
## Reproduction Steps
Look at the bottom of some Bridgeliner newsletters with the redesign. You'll see there's redundant language in the footer:

"You subscribed to this list through Bridgeliner or at one of our events. 
You subscribed to this list through https://bridgeliner.com or at one of our events."

## Expected Results
"You subscribed to this list through https://bridgeliner.com or at one of our events."

## Actual Results
"You subscribed to this list through Bridgeliner or at one of our events. 
You subscribed to this list through https://bridgeliner.com or at one of our events."

### Additional information:
 - BTID-437
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recSnMjSnQxVjw04v) - (may include image attachments)

### Submitted by
Name: Ben
Email: 
Slack ID:

**Comment by kassanj** [comment]
This bug only appears in the redesign theme. I checked all the templates (compiled and raw) and there are no replicates of this code. I also noticed that staging and development test emails do not have this bug, only production. I'm going to move this ticket to blocked and revisit the bug again once the latest code has been pushed to production.

**Comment by ErnieAtLYD** [comment]
This has to do [with the MailChimp merge tags](https://mailchimp.com/help/customize-your-footer-content/):
`*|LIST:DESCRIPTION|*` inserts your list's permission reminder 
`*|HTML:LIST_ADDRESS_HTML|*` inserts your physical address and an "Add us to your address book" link that points to the vCard (.vcf) file with your address details.

Because this was also duplicated in the template, it's being shown twice. I'll remove it from the newsletter template.
